define(function() {
    return {
		language:'language/lang',
        wanlearnconfig:'ntwk/wanlearnconfig?type=notshowpass',
        wanlearntrigerloopmac:'ntwk/wanlearntrigerloopmac',
        slave_setup:'hilink/slave_setup',
        client_heartbeat:'ntwk/client_heartbeat',
        ntwkcap_compare:'hilink/ntwkcap_compare',
        encpubkey: 'system/encpubkey',
        pwd: 'system/pwd',
        heartbeat: 'system/heartbeat',
        guideheartbeat: 'system/guideheartbeat',
        wansearchcontrol:"ntwk/wansearchcontrol",
        wan:'ntwk/wan?type=active',
        doublewan:'ntwk/wan',
        swan:'ntwk/swan',
        hilink_status:'hilink/hilink_status',
        wlanmode:'system/wlanmode',
        privacypolicy:'app/privacypolicy',
        userbehavior:'system/userbehavior',
        sntp:'ntwk/sntp',
        guide:'system/guide',
        location:'system/location',
        wlanradio:'ntwk/wlanradio',
        wlanwps:'ntwk/wlanwps',
        restorestate:'system/restorestate',
        wlanintelligent:'ntwk/wlanintelligent',
        wlan_easymesh:'ntwk/wlan_easymesh',
        l2topo:'device/l2topo',
        WlanGuideBasic:'ntwk/WlanGuideBasic?type=notshowpassall',
        WlanGuideBasic_scram:'ntwk/WlanGuideBasic_scram?type=notshowpassall',
        wlanwifisync:'ntwk/wlanwifisync',
        access_auth:"ntwk/access_auth",
        diagnose_wlan_basic:'system/diagnose_wlan_basic?type=1',
        diagnose_wlan_basic2:'system/diagnose_wlan_basic?type=2',
        diagnose_wlan_basic3:'system/diagnose_wlan_basic?type=3',
        deviceinfo:'system/deviceinfo',
        deviceinfo_wizard:'system/deviceinfo?type=wizards',
        app_wizard:'app/wizards',
        //home start
        device_count:'system/device_count',
        HostInfo:'system/HostInfo',
        MultiHostInfo:'system/MultiHostInfo',
        wandetect:'ntwk/wandetect',
        wan:'ntwk/wan?type=active',
        wandiagnose:'ntwk/wandiagnose',
        wlanradio:'ntwk/wlanradio',
        WlanGuideBasic:'ntwk/WlanGuideBasic?type=notshowpassall',
        wlantimeswitch:'ntwk/wlantimeswitch',
        sdcapacity:'sdcard/sdcapacity',
        onlinestate:'system/onlinestate',
        hilinkwaninfo:'ntwk/hilinkwaninfo',
        repeaterinfo:'ntwk/repeaterinfo',
        repeaterstate:'ntwk/repeaterstate',
        RepeaterDial_scram:'ntwk/RepeaterDial_scram',
        RepeaterDial:'ntwk/RepeaterDial',
        repeaterdiag:'ntwk/repeaterdiag',
        wifiscanresult:'ntwk/wifiscanresult',
        // home end
        // devices begin
        getmacaddress: "ntwk/getmacaddress",
        topology:"device/topology",
        slavedevinfo: "hilink/slavedevinfo",
        ledstatus:"hilink/ledstatus",
        wlanfilterenhance:"ntwk/wlanfilterenhance",
        qosclass_host:"app/qosclass_host",
        ioc_device_capacity:"system/ioc_device_capacity.json",
        changedevicename: "system/changedevicename",
        // devices end
        //lan
        lan:'ntwk/lan',
        lan_ipaddressreserve:'ntwk/lan_ipaddressreserve',
        lan_server:'ntwk/lan_server',
        lan_all:'ntwk/lan_all',
        //upnp
        lan_upnp:'ntwk/lan_upnp',
        lan_upnp_portmapping:'ntwk/lan_upnp_portmapping',
        // qos start
        qos:'app/qos',
        tgpgameinfo:'app/tgpgameinfo',
        tgpgameswitch:'app/tgpgameswitch',
        speedtest:'app/speedtest',
        //parentcontrol
        timecontrol:'ntwk/timecontrol',
        urlfilter:'ntwk/urlfilter',
        // ddns
        ddns:'ntwk/ddns',
        // ddnsstatus
        ddnsstatus:'ntwk/ddnsstatus',
        //powerline
        plcenableall:"ntwk/plcenableall",
        powernetwork:"ntwk/powernetwork",
        plc_web_switch_siso:"ntwk/plc_web_switch_siso",
        //firewall
        firewall:'ntwk/firewall',
        //nat
        application:"app/application",
        applicationitems:"app/applicationitems",
        portmapping:"ntwk/portmapping",
        porttrigger:"ntwk/porttrigger",
        //samba
        fsstatus:'usbstorage/fsstatus',
        lan_host:'ntwk/lan_host',
        usbaccount:'usbstorage/usbaccount',
        usbchangemode:'system/usbchangemode',
        wandiagnose:'ntwk/wandiagnose',
        repeaterstate:"ntwk/repeaterstate",
        sambaanonymous:"usbstorage/sambaanonymous",
        //dlna
        dms:"app/dms",
        // aria2
        aria2Infos:"openee/plugin/infos",
        aria2_upload:"sdcard/fileupload",
        aria2_getBtPath:"openee/3d/com.huawei.hilink.aria.v2/aria/getBtPath",
        aria2_transRpc:"openee/3d/com.huawei.hilink.aria.v2/aria/transRpc",
        aria2_getUriByGid:"openee/3d/com.huawei.hilink.aria.v2/aria/getUriByGid",
        aria2_transRpcArrayTemp:"openee/3d/com.huawei.hilink.aria.v2/aria/transRpcArrayTemp",
        aria2_DownInfo: "openee/3d/com.huawei.hilink.aria.v2/aria/getDownInfoWeb/encoding=gzip",
        aria2_saveOption:"openee/3d/com.huawei.hilink.aria.v2/aria/saveOption",
        aria2_tellStopped:"openee/3d/com.huawei.hilink.aria.v2/aria/getRecordWeb/encoding=gzip",
        aria2_delRecord:"openee/3d/com.huawei.hilink.aria.v2/aria/delRecord",
        aria2_diskPartCount:"openee/3d/com.huawei.hilink.aria.v2/aria/getDiskPartCount",
        aria2_getDiskInfo:"openee/3d/com.huawei.hilink.aria.v2/aria/getDiskInfo",
        deletefile:'sdcard/deletefile',
        sdfile:'sdcard/sdfile',
        //smartpush
        hotaservice:"system/hotaservice",
        //urlsec
        urlsec:"ntwk/urlsec",
        //dmz
        dmz:"ntwk/dmz",
        user_login_nonce:"system/user_login_nonce",
        user_login_proof:"system/user_login_proof",
        user_login:"system/user_login",
        useraccount:"system/useraccount",
        useraccount_scram:"system/useraccount_scram",
        // guide
        wlandbho:"ntwk/wlandbho",
        getpairstatus:"ntwk/getpairstatus",
        WlanTestStatus:"ntwk/WlanTestStatus",
        //wlanguest
        guest_network:"ntwk/guest_network?type=notshowpassall",
        guest_network_resttime:"ntwk/guest_network_resttime",
        guest_network_limitrate:"ntwk/guest_network_limitrate",
        // upgrade
        multiwan:'ntwk/multiwan',
        autoupgrade: "system/autoupgrade",
        onlineupg:'system/onlineupg',
        online_check:"system/online_check",
        hota_redirect_omit:"system/hota_redirect_omit",
        uploadimage:'device/uploadimage',
        hilinkwaninfo:'ntwk/hilinkwaninfo',
        ipv6_enable:'ntwk/ipv6_enable',
        ipv6_wan:'ntwk/ipv6_wan',
        ipv6_lan:'ntwk/ipv6_lan',
        // logout
        user_logout:'system/user_logout',
        // mirror
        diagnose_crash_devlist:'system/diagnose_crash_devlist',
        diagnose_crash:'system/diagnose_crash',
        mirror:'ntwk/mirror',
        ip_capture:'ntwk/ipcapture',
        // 强制升级
        forceupg:'system/forceupg',
        forceupgcfg:'system/forceupgcfg',
        forceupglater:'system/forceupglater',
        // 重定向
        smartpush_autoupg:'app/smartpush_autoupg',
        zjct_redirect:'ntwk/zjct_redirect',
        andlink_lock_net: 'ntwk/andlink_lock_net',
        // samrtvpn
        smartvpn: 'ntwk/smartvpn',
        l2tp: 'ntwk/l2tp',
        pptp: 'ntwk/pptp',
        smartvpnurl: 'ntwk/smartvpnurl',
        smartvpnmaclist: 'ntwk/smartvpnmaclist',
        // wlanintelligent
        backhaul: 'ntwk/backhaul',
        wlanelink: 'ntwk/wlanelink',
        // wansettings
        ethportmode:'app/ethportmode',
        // IPTV 设置
        iptv:'ntwk/iptv',
        // ntwkportrate
        ethnegotiation:'ntwk/ethnegotiation',
        // diagnose
        dnsdiagnose:'system/dnsdiagnose',
        diagnose_ping:'system/diagnose_ping',
        httpdiagnose:'system/httpdiagnose',
        diagnose_button:'system/diagnose_button',
        diagnose_led:'system/diagnose_led',
        wizard_wifi:'system/wizard_wifi',
        diagnose_usb:'system/diagnose_usb',
        bi_statistics:'system/bi_statistics',
        uploadconfigfile:'device/uploadconfigfile',
        uploadconfigfileresult:'device/uploadconfigfileresult',
        // 定制页面
        explicit:'system/explicit',
        provcode:'system/provcode',
        tr069:'app/tr069',
        mcast:'ntwk/mcast',
        wlantimeaccelerate:"ntwk/wlanTimingAccelerate",
        timedredial:"ntwk/timedredial",
        processstatus:'system/processstatus',
        wlanpowertimeswitch:'ntwk/wlanpowertimeswitch',
        rebootplan:'system/rebootplan',
        fwmacfilter:'ntwk/fwmacfilter',
        nfc_switch: 'bsp/nfc_switch'
    }
})