define(function() {
    return {
    "logout":"退出登录",
    "index.lang.zh":"中文（简体）",
    'Download_Apps':'应用下载',
    'Huawei_SmartHome':"智慧生活 App",
    'Huawei_SmartHome_custom':"移动和家亲 APP",
    'footer_about':'关于产品',
    'footer_shop':"华为商城",
    'footer_forum':"花粉论坛",
    'footer_contact':'联系方式',
    'footer_wechat': "官方微信",
    'Legal_Notices':'法律声明',
    "Huawei_Privacy_Policy":"隐私声明",
    "Open_Source_Statement":"开源软件声明",
    "End_User_License_Agreement":"最终用户许可协议",
    "pwdstrength":"密码强度",
    'pwdstrength_weak':"弱",
    'pwdstrength_medium':"中",
    'pwdstrength_strong':"强",
    "cancel":"取消",
    "continue":"继续",
    "sure":"确定",
    'back':'返回',
    'index.save':"保存",
    'next':'下一步',
    'tryafain':'再试试',
    'loading':"正在保存您的配置，请耐心等待...",
    "index.day":"天",
    "index.day.one":"天",
    "index.hour":"小时",
    "index.hour.one":"小时",
    "index.minute":"分钟",
    "index.minute.one":"分钟",
    "index.second":"秒",
    "index.second.one":"秒",
    "index.system.time":"系统时间",
    "index.operate":"操作",
    "week.day_0":"周日",
    "week.day_1":"周一",
    "week.day_2":"周二",
    "week.day_3":"周三",
    "week.day_4":"周四",
    "week.day_5":"周五",
    "week.day_6":"周六",
    "index.open":"开启",
    "index.noopen":"不开启",
    "index.close":"关闭",
    'index.cannone':"（可不填）",
    "Menu.range_err":"取值范围是[{0}]",
    "Menu.integer_err":"必须是整数",
    'save':"保存",
    "helpInfo":"页面帮助",
    'index.pwdZero_err':"密码不能为空",
    "Menu.pwd_nomatch_err":"确认密码必须和之前输入的密码完全一致",
    "index.notempty":"{0}不能为空",
    'wan.pppusername':"宽带帐号",
    'wan.ppppassword':"宽带密码",
    'wan.macconetype':"MAC 克隆",
    'wan.macconenone':"不使用 MAC 克隆",
    'wan.macconecurrent':"使用您电脑的 MAC 地址",
    'wan.macconemanual':"手动输入 MAC 地址",
    'wan.macconeaddress':"MAC 地址",
    'wan.ipaddress':"IP 地址",
    'wan.maskaddress':"子网掩码",
    'wan.defaultgate':"默认网关",
    'wan.IPv4PriDns':"首选 DNS 服务器",
    'wan.IPv4SecDns':"备用 DNS 服务器",
    "wan.macformat":"MAC 地址格式：XX-XX-XX-XX-XX-XX<br>或 XX:XX:XX:XX:XX:XX 或 XXXXXXXXXXXX",
    'wan.passworderror':"密码长度为0~64个字符",
    'wan.macaddrerr':"MAC 地址错误。请参考格式说明，核对后重新输入，并且第一段 XX 不能是奇数",
    "wan.ipv4addrerr":"请输入有效的 IP 地址，如 192.168.33.1",
    "wan.v4maskerr_empty":"子网掩码不能为空",
    "wan.v4maskerr":"子网掩码不合法",
    "wan.v4gatewayerr_empty":"默认网关不能为空",
    "wan.v4gatewayerr":"默认网关不合法",
    "wan.IPv4SameAddress_err":"IP 地址不能与默认网关相同",
    "wan.v4AddrConflictLanerr":"IP 地址和 路由器局域网 IP 地址冲突，请重新输入",
    "wan.v4pridnserr_empty":"首选 DNS 服务器不能为空",
    "wan.v4pridnserr":"首选 DNS 服务器不合法",
    "wan.v4secdnserr":"备用 DNS 服务器不合法",
    'wan.connectunknown':'宽带网络连接失败，请联系您的宽带运营商（如：电信、联通等）',
    'wan.connectunknown_custom':'宽带网络连接失败，请联系您的宽带运营商',
    'wan.ppp_ErrAuthFail':"宽带帐号或密码错误，请重新输入。如果忘记帐号密码，请联系您的宽带运营商（如：电信、联通等）。",
    'wan.ppp_ErrAuthFail_custom':"宽带帐号或密码错误，请重新输入。如果忘记帐号密码，请联系您的宽带运营商。",
    'wan.ppp_ErrAuthFail_info':"帐号或密码错误",
    'wan.ppp_ErrAuthFail_error1':'1、如果忘记帐号或密码，您可以<a id="learnoldlink" href="javascript:void(0)" class="underline-link" onclick="langClick(\'learnold\')">一键从旧路由器获取帐号和密码</a>',
    'wan.ppp_ErrAuthFail_error2':'2、请确认帐号是否欠费，或联系您的<a href="javascript:void(0)"class="underline-link" onclick="langClick(\'operator\')">宽带运营商</a>',
    'wan.ppp_ErrAuthFail_error2_custom':'2、请确认帐号是否欠费，或联系您的宽带运营商',
    'wan.ppp_ErrConnectFail':"未获取到 IP 地址",
    'wan.ppp_ErrAuthUserLimit':"已经有其它路由器或电脑正在使用此宽带帐号，请先断开其它宽带连接，等待三分钟后，再重新设置路由器上网。",
    'wan.ppp_ErrAuthUserLimit_2':"已经有其它路由器或电脑正在使用此宽带帐号，请先断开其它宽带连接，等待三分钟后，再重新诊断",
    'wan.ppp_ErrAuthUserLimit_info':"您的宽带运营商（如：电信、联通等）不允许多台设备同时使用同一个宽带帐号。如果您希望通过此路由器上网，请先断开其他使用此宽带帐号的设备连接，等待三分钟后，再重新设置路由器上网。如仍无法上网，请联系宽带运营商。",
    'wan.ppp_ErrAuthUserLimit_info_custom':"您的宽带运营商不允许多台设备同时使用同一个宽带帐号。如果您希望通过此路由器上网，请先断开其他使用此宽带帐号的设备连接，等待三分钟后，再重新设置路由器上网。如仍无法上网，请联系宽带运营商。",
    'wan.ppp_ErrAuthMacLimit':"您的宽带运营商（如：电信、联通等）限制了新路由接入。您可以使用“MAC 地址克隆” ，或直接联系宽带运营商解决。",
    'wan.ppp_ErrAuthMacLimit_custom':"您的宽带运营商限制了新路由接入。您可以使用“MAC 地址克隆” ，或直接联系宽带运营商解决。",
    'wan.ppp_ErrAuthMacLimit_err':'MAC 地址限制',
    'wan.ppp_ErrAuthMacLimit_errinfo':'您的宽带运营商限制了您的路由器接入，您可以使用“MAC地址克隆”或<a id="learnoldlink" href="javascript:void(0)" style="text-decoration:underline;" class="link" onclick="langClick(\'learnold\')">一键从旧路由器获取</a>，若获取失败，请联系您的<a style="text-decoration:underline;" class="link" onclick="langClick(\'operator\')">宽带运营商</a>',
    'wan.ppp_ErrAuthMacLimit_errinfo_custom':'您的宽带运营商限制了您的路由器接入，您可以使用“MAC地址克隆”或<a id="learnoldlink" href="javascript:void(0)" style="text-decoration:underline;" class="link" onclick="langClick(\'learnold\')">一键从旧路由器获取</a>，若获取失败，请联系您的宽带运营商',
    'wan.ppp_ErrNoAnswer':'路由器无法连接互联网。请确保路由器的 WAN 网口正确连接后，重新设置路由器。若仍然无法上网，请联系您的宽带运营商（如：电信、联通等）',
    'wan.ppp_ErrNoAnswer_custom':"路由器无法连接互联网。请确保路由器的 WAN 网口正确连接后，重新设置路由器。若仍然无法上网，请联系您的宽带运营商。",
    'wan.ppp_ErrNoAnswer_lanwan':'路由器无法连接互联网。请确保路由器的网口正确连接后，重新设置路由器。若仍然无法上网，请联系您的宽带运营商（如：电信、联通等）。',
    'wan.ppp_ErrNoAnswer_lanwan_custom':'路由器无法连接互联网。请确保路由器的网口正确连接后，重新设置路由器。若仍然无法上网，请联系您的宽带运营商。',
    'wan.ppp_UserLen_err':'宽带帐号超长',
    'wan.ppp_PasswordLen_err':'宽带密码超长',
    'wan.ppp_ServiceNameLen_err':'服务名超长',
    'wan.ppperror_info':'详细信息',
    'wan.ppp_ErrNoAnswer_info':"拨号失败",
    'wan.wifi.wifilist':'当前可用的 Wi-Fi 列表',
    'wan.wifi.choose':'请选择要连接的 Wi-Fi',
    'wan.wifi.connectto':'连接 Wi-Fi：{0}',
    'wan.wifi.scaning':'正在扫描可用的 Wi-Fi...',
    'wan.wifi.scanagain':'重新扫描',
    'wan.wifi.connecting':'正在连接{0} Wi-Fi...',
    'wan.wifi.name':"Wi-Fi 名称",
    'wan.wifi.password':"Wi-Fi 密码",
    'wan.wifi.wep'           :'认证类型',
    'wan.wifi.wep_Open'          :'开放密钥',
    'wan.wifi.wep_Shared'        :'共享密钥',
    'wan.wifi.WEPindex'      :'WEP 密钥序号',
    "wan.name.err":"{0}不能为空",
    "wan.wepkey.err":"密码有误，请重新输入",
    "wan.wifi.passerr":"密码长度要求为{0}个字符",
    'wan.wifi.connected.failed':'Wi-Fi 连接失败，请重新选择或者手动输入',
    'wan.wifi.connected.password.err':'Wi-Fi 密码只能由英文、数字、空格和特殊字符（如~,`,!,@,#,$,%,^,&,*,(),-,_,+,=等）组成',
    'wan.wifi.manualadd':'添加其他网络',
    'wan.wifi.secmode':'安全模式',
    "wan.wifi.secopt_Open":"NONE",
    "wan.wifi.secopt_WEP":"WEP",
    "wan.wifi.secopt_WPA-PSK":"WPA-PSK",
    "wan.wifi.secopt_WPA2-PSK":"WPA2-PSK",
    "wan.wifi.secopt_WPA/WPA2-PSK":"WPA/WPA2-PSK",
    'content.internet.linedown':"未检测到入户网线，请检查网线。",
    "wifi.channel":"信道",
    'footer.wechat.poptitle': "华为路由器官方微信订阅号",
    'footer.wechat.slogan': "智慧家庭，畅想互联！",
    'footer.wechat.detail': "我们将为您提供最领先产品的资讯动态，以及产品购买、使用和售后服务等信息。",
    'index.magic':"扫描或点击下载智慧生活 App",
    'index.magic_custom':"扫描下载移动和家亲 APP",
    "footer.safeinformation":"安全信息",
    'Touch.wan.guangmaoed'             :"光猫故障",
    'Touch.wan.guangmaobreakdown'      :"检查光猫面板上所有灯是否都是绿灯常亮，如果红灯闪烁请检查线路是否正常。",
    'footer.softversion':'软件版本：',
    'footer.copyright':'版权所有©华为终端有限公司 2012-2021',
    "notice":"提示",
    'content.wifi.setssid2g':"2.4G Wi-Fi",
    'content.wifi.setssid5g':"5G Wi-Fi",
    "wifi.ssid.factory.err":'请不要使用默认的 Wi-Fi 名称 "{0}"',
    "wifi.ssid.reserved":'您设置的 Wi-Fi 名称“{0}”有潜在的冲突风险，请重新设置',
    "wlanintelligent.upstream.syncerr":"正在同步其他智联设备，请稍候...",
    "wlanintelligent.upstream.syncok":"组网智联设备已同步修改",
    "Menu.lenrange_err":"长度范围是[{0}]",
    "Menu.less_than_err":"必须是小于{0}的数",
    "Menu.max_length_err":"最大长度为{0}",
    // Nav Begin
    'home':"主页",
    'internet':"我要上网",
    'wifi':'我的 Wi-Fi',
    'qos':"智能带宽",
    'devicecontrol':"终端管理",
    'more':"更多功能",
    // Nav End
    "footer.touchUI":"移动版",
    // Menu
    'deviceinfo':"路由器信息",
    'upgrade':"升级管理",
    'netsettings':"网络设置",
    'smartqos':"网络带宽",
    'remote':"远程访问",
    'lan':"局域网",
    'vpn':"虚拟专用网 VPN",
    'iptv':'IPTV 设置',
    'upnp':"UPnP",
    "wlanintelligent": "智联设置",
    "wlanintelligent_custom":"智能组网",
    'elink':"e-Link设置",
    'ipv6':"IPv6",
    'wifisettings':"Wi-Fi 设置",
    'wlanadvance':"Wi-Fi 高级",
    'wlanaccess':"Wi-Fi 访问控制",
    'wlanguest':"客人 Wi-Fi",
    'repeater':"Wi-Fi 中继",
    'wlaneco':"Wi-Fi 定时",
    'remoteset':"动态域名服务 DDNS",
    'share':"存储共享",
    'samba':"文件共享",
    'aria2':"Aria2 下载",
    'dlna':"DLNA",
    'safesettings':"安全设置",
    'firewall':"防火墙",
    'nat':"NAT 服务",
    'dmz':"DMZ 主机",
    'parentcontrol':"儿童上网保护",
    "powerline":"电力线设置",
    'urlsec':"上网安全防护",
    'systemsettings':"系统设置",
    "nfc": "NFC",
    'account':"修改登录密码",
    'sntp':"网络时间",
    'reset':"备份与恢复",
    'provcode':"省码设置",
    'operatorfuc':"运营商功能设置",
    'diagnose':"诊断",
    'wansettings':"网口设置",
    'ntwkportrate':"网口设置",
    'mirror':"开发者选项",
    'application':"应用",
    'smartpush':"辅助功能",
    'userbehavior':"用户体验改进计划",
    'toolbox':"工具箱",
    'powernetwork':"子路由配置",
    "wanrate": "网口设置",
    'mcast':"IGMP设置",
    'wlantimeaccelerate':"Wi-Fi 定时加速",
    'timeredial':"定时重拨",
    'routestatus':"路由器状态",
    'tr069':"TR069 服务",
    'intelligence':"Wi-Fi 智能模式",
    'reboot':"重启计划",
    'macfilter':"MAC 过滤",
    'lead.title':"欢迎使用{0}",
    'lead.network':"轻松配网",
    'lead.network.tip':"新手也会配网，宽带帐号密码从旧路由一键获取",
    'lead.remote':"远程管理",
    'lead.remote.tip':"通过 App 随时随地查看您家的家庭网络，一键剔除蹭网设备",
    'lead.security':"安全防护",
    'lead.security.tip':"识别虚假交易，防止暴力破解，屏蔽诈骗木马病毒等网页",
    'lead.service':"智能服务",
    'lead.service.tip':"带宽提升，游戏更流畅，孩子上网轻松管理，购物卡、优惠券天天发放",
    'lead.app.tip':"使用 App，随时随地管理接入您网络的设备",
    'lead.app.download':"扫描下载智慧生活 App",
    'lead.manual.manage':"暂不下载，开始配置",
    'login.notice':"提醒：确保密码没有错误的情况下，您可尝试清空浏览器缓存，重新登陆路由器。",
    "pwd.max_length_help":"输入字符已达最大长度{0}",
    "wlan.ssid.help":"少数终端设备（手机）可能不支持{0} SSID 或特殊字符"
    }
})